{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[[]]},"kind":"symbol","topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal\/CardRevealService","doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal\/PinChangeService","doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal\/PinRevealService"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/adyencardreveal"]},{"paths":["\/documentation\/adyencardreveal"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"AdyenCardReveal","role":"collection","modules":[{"name":"AdyenCardReveal"}],"externalID":"AdyenCardReveal","symbolKind":"module","roleHeading":"Framework"},"sections":[],"identifier":{"url":"doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal","interfaceLanguage":"swift"},"references":{"doc://com.adyen.AdyenCardReveal/documentation/AdyenCardReveal/AdyenCardRevealVersionString":{"fragments":[{"kind":"identifier","text":"AdyenCardRevealVersionString"}],"abstract":[{"type":"text","text":"Project version string for AdyenCardReveal."}],"title":"AdyenCardRevealVersionString","identifier":"doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal\/AdyenCardRevealVersionString","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/adyencardreveal\/adyencardrevealversionstring"},"doc://com.adyen.AdyenCardReveal/documentation/AdyenCardReveal/PinRevealService":{"title":"PinRevealService","url":"\/documentation\/adyencardreveal\/pinrevealservice","navigatorTitle":[{"text":"PinRevealService","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PinRevealService","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal\/PinRevealService"},"doc://com.adyen.AdyenCardReveal/documentation/AdyenCardReveal/PinChangeService":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PinChangeService"}],"navigatorTitle":[{"kind":"identifier","text":"PinChangeService"}],"type":"topic","url":"\/documentation\/adyencardreveal\/pinchangeservice","role":"symbol","abstract":[],"identifier":"doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal\/PinChangeService","kind":"symbol","title":"PinChangeService"},"doc://com.adyen.AdyenCardReveal/documentation/AdyenCardReveal/CardRevealService":{"abstract":[],"title":"CardRevealService","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardRevealService"}],"navigatorTitle":[{"text":"CardRevealService","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal\/CardRevealService","url":"\/documentation\/adyencardreveal\/cardrevealservice","kind":"symbol"},"doc://com.adyen.AdyenCardReveal/documentation/AdyenCardReveal":{"abstract":[],"title":"AdyenCardReveal","role":"collection","url":"\/documentation\/adyencardreveal","type":"topic","kind":"symbol","identifier":"doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal"},"doc://com.adyen.AdyenCardReveal/documentation/AdyenCardReveal/AdyenCardRevealVersionNumber":{"type":"topic","url":"\/documentation\/adyencardreveal\/adyencardrevealversionnumber","kind":"symbol","abstract":[{"type":"text","text":"Project version number for AdyenCardReveal."}],"role":"symbol","title":"AdyenCardRevealVersionNumber","fragments":[{"kind":"identifier","text":"AdyenCardRevealVersionNumber"}],"identifier":"doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal\/AdyenCardRevealVersionNumber"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"title":"Variables","identifiers":["doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal\/AdyenCardRevealVersionNumber","doc:\/\/com.adyen.AdyenCardReveal\/documentation\/AdyenCardReveal\/AdyenCardRevealVersionString"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"}]}]}